modLoader="javafml"
loaderVersion="${loaderForgeV}"
issueTrackerURL="${gitUrl}/issues"
license="${license}"


[[mods]]
modId="${modId}"
version="${modV}"
displayName="${modName}"
displayURL="${gitUrl}"
logoFile= "${modId}.png"
authors="${modAuthors}"
description='''${modDesc}'''


[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="${loaderForgeVRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[${mcV},${mcVRangeMax})"
ordering="NONE"
side="BOTH"
