plugins {
    id "common"
    id "net.neoforged.moddev"
}

version "common+${mcV}"

neoForge {
    neoFormVersion.set "${mcV}-${neoFormV}"

    parchment {
        mappingsVersion.set mapsV
        minecraftVersion.set mapsMcV
    }
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}

dependencies {
    implementation "org.spongepowered:mixin:0.8.7"
    implementation "io.github.llamalad7:mixinextras-common:0.5.2"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.5.2"
}

configurations {
    commonJava {
        canBeResolved false
        canBeConsumed true
    }

    commonResources {
        canBeResolved false
        canBeConsumed true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.files
}