plugins {
    id "common"
    id "org.spongepowered.gradle.vanilla" version "0.2.2"
}

minecraft {
    version mcV
    accessWideners file("src/main/resources/aw.accesswidener")
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.7"
    compileOnly "io.github.llamalad7:mixinextras-common:0.5.2"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.5.2"
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}

configurations {
    commonJava {
        canBeResolved false
        canBeConsumed true
    }

    commonResources {
        canBeResolved false
        canBeConsumed true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.files
    commonResources sourceSets.main.resources.sourceDirectories.files
}