plugins {
    id "java"
}

group "com.swacky.${modId}"

base {
    archivesName.set "${modId}-${modV}"
}

java {
    toolchain.languageVersion.set JavaLanguageVersion.of(javaV)
}

processResources {
    var replaceProperties = [
            packFormatV: packFormatV
    ]

    inputs.properties replaceProperties

    filesMatching("pack.mcmeta") {
        expand replaceProperties
    }

    exclude "META-INF/accesstransformer.cfg"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set JavaLanguageVersion.of(javaV).asInt()
}

['apiElements', 'runtimeElements'].each { variant ->
    configurations."${variant}".outgoing {
        capability("${group}:${base.archivesName.get()}:${version}")
        capability("${group}:${modId}-${project.name}-${mcV}:${version}")
        capability("${group}:${modId}:$version")
    }
}