plugins {
    id "idea"
    id "java"
    id "maven-publish"
    id "signing"
}

group "com.swacky"
version "${project.name}-mc${mcV}"

base {
    archivesName.set "${modId}-${modV}"
}

java {
    JavaLanguageVersion javaVersion = JavaLanguageVersion.of(javaV);
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    toolchain.languageVersion = javaVersion

    // This artifact isn't used, it is just to ensure that Javadoc {@link ...} references are correct
    withJavadocJar()
    withSourcesJar()
}

processResources {
    var replaceProperties = [
            modId          : modId,
            packFormatMinV : packFormatMinV,
            packFormatMaxV : packFormatMaxV
    ]

    inputs.properties replaceProperties

    filesMatching(["pack.mcmeta", "resourcepacks/*/pack.mcmeta"]) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add("-Xlint:deprecation")
    options.encoding = "UTF-8"
    options.release.set JavaLanguageVersion.of(javaV).asInt()
}

jar {
    exclude "**/.cache"
}

tasks.named("javadocJar", Jar) {
    archiveClassifier = "javadoc-unused"
}

tasks.named("sourcesJar", Jar) {
    exclude "**/.cache"
}

tasks.named("compileTestJava") {
    enabled = false
}

tasks.named("processTestResources") {
    enabled = false
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

tasks.register("pseudoJavadocJar", Jar) {
    archiveClassifier = "javadoc"
}

["apiElements", "runtimeElements", "sourcesElements"].each { variant ->
    configurations."${variant}".outgoing {
        capability "${group}:${base.archivesName.get()}:${version}"
        capability "${group}:${modId}-${project.name}-${mcV}:${version}"
        capability "${group}:${modId}:$version"
    }
}

File secretsFile = rootProject.file("secrets.properties")

if (secretsFile.exists()) {
    secretsFile.withInputStream { stream -> {
            Properties secrets = new Properties()

            secrets.load(stream)
            secrets.forEach {
                key, value -> project.ext.set((String) key, value)
            }
        }
    }

    afterEvaluate {
        publishing {
            publications {
                mavenJava(MavenPublication) {
                    groupId = "io.github.swackyy"
                    artifactId = "${modId}-${project.name}"
                    version = "${modV}-mc${mcV}"

                    from components.java
                    artifact tasks.named("pseudoJavadocJar")

                    artifacts.removeAll { artifact ->
                        artifact.classifier == "javadoc-unused"
                    }

                    pom {
                        name = "${modName} ${project.name}"
                        description = modSummary
                        url = gitUrl

                        withXml {
                            Object dependencies = asNode().dependencies[0]

                            if (dependencies != null) {
                                List targets = dependencies.dependency.findAll { dep ->
                                    String groupId = dep.groupId.text()

                                    groupId.contains("jei") ||
                                    groupId.contains("minecraftforge") ||
                                    dep.artifactId.text().contains("spark")
                                }

                                targets.each { dep ->
                                    dependencies.remove(dep)
                                }
                            }
                        }

                        licenses {
                            //noinspection GroovyAssignabilityCheck
                            license {
                                name = license
                            }
                        }

                        scm {
                            url = "github.com"
                            connection = "scm:git:git:github.com"
                            developerConnection = "scm:git:ssh://github.com"
                        }

                        developers {
                            developer {
                                id = "swackyy"
                                name = modAuthorsDisplay
                            }
                        }
                    }

                    suppressPomMetadataWarningsFor("apiElements")
                    suppressPomMetadataWarningsFor("javadocElements")
                    suppressPomMetadataWarningsFor("runtimeElements")
                    suppressPomMetadataWarningsFor("sourcesElements")
                }
            }

            repositories {
                maven {
                    name = "MavenCentral"
                    url = "https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2"

                    credentials {
                        username = getProperty("secretsMavenCentralUsername")
                        password = getProperty("secretsMavenCentralPassword")
                    }
                }
            }
        }

        plugins.withType(MavenPublishPlugin).configureEach {
            signing {
                String id = findProperty("secretsSigningId")
                String key = findProperty("secretsSigningKey")
                String password = findProperty("secretsSigningPassword")

                if (id && key && password) {
                    useInMemoryPgpKeys(id, key, password)
                    sign publishing.publications.mavenJava
                } else {
                    System.err.println "Could not sign project ${project.name}"
                    required = false
                }
            }
        }
    }
}