plugins {
    id "common"
    id "java"
}

java {
    withSourcesJar()
}

configurations {
    commonJava {
        canBeResolved true
    }

    commonResources {
        canBeResolved true
    }
}

dependencies {
    compileOnly(project(":loader:common")) {
        capabilities {
            requireCapability "${group}:${modId}"
        }
    }

    commonJava project(path: ":loader:common", configuration: "commonJava")
    commonResources project(path: ":loader:common", configuration: "commonResources")
}

processResources {
    var replaceProperties = [
            license                              : license,
            loaderForgeV                         : loaderForgeV,
            loaderForgeVRange                    : loaderForgeVRange,
            loaderNeoV                           : loaderNeoV,
            loaderNeoVRange                      : loaderNeoVRange,
            loaderFabricVRange                   : loaderFabricVRange,
            modId                                : modId,
            modV                                 : modV,
            modAuthors                           : modAuthorsDisplay,
            mcV                                  : mcV,
            modName                              : modName,
            gitUrl                               : gitUrl,
            issuesUrl                            : "${gitUrl}/issues",
            curseUrl                             : curseUrl,
            modDescFabric                        : modDescMin,
            modDesc                              : "${modDescMin}\n${modDescSrc}: ${gitUrl}\n${modDescWiki}: ${gitUrl}/wiki",
            loaderFabricForgeConfigApiPortVRange : loaderFabricForgeConfigApiPortVRange,
            javaV                                : javaV
    ]
    inputs.properties replaceProperties

    filesMatching(["META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
        expand replaceProperties
    }

    dependsOn configurations.commonResources
    from configurations.commonResources
}

jar {
    manifest {
        attributes([
                "Specification-Title"    : modId,
                "Specification-Vendor"   : modAuthors,
                "Specification-Version"  : modV,
                "Implementation-Title"   : project.name,
                "Implementation-Version" : modV,
                "Implementation-Vendor"  : modAuthors,
                "MixinConfigs"           : "${modId}.mixins.json"
        ])
    }

    dependsOn configurations.commonJava
    from configurations.commonJava/*{
        exclude "com/swacky/ohmega/datagen/**"
    }*/
    dependsOn configurations.commonResources
    from configurations.commonResources
}

tasks.withType(JavaCompile).configureEach {
    dependsOn configurations.commonJava
    source configurations.commonJava/*{
        exclude "com/swacky/ohmega/datagen/**"
    }*/
}