plugins {
    id "common"
    id "java"
    id "me.modmuss50.mod-publish-plugin"
}

configurations {
    commonJava {
        canBeResolved = true
    }

    commonResources {
        canBeResolved = true
    }
}

dependencies {
    compileOnly(project(":loader:common")) {
        capabilities {
            requireCapability "${group}:${modId}"
        }
    }

    commonJava project(path: ":loader:common", configuration: "commonJava")
    commonResources project(path: ":loader:common", configuration: "commonResources")
}

processResources {
    String modDesc = modSummary;

    if (project.name != "fabric") {
        modDesc =
                "\n"                                       +
                "View the source code here: ${gitUrl}\n"   +
                "Or visit the wiki here: ${gitUrl}/wiki\n" +
                "And join the discord here: ${discordUrl}"
    }

    if (!modChanges.empty) {
        modDesc += "\n\nChanges this version:\n${modChanges}";
    }

    var replaceProperties = [
            license                              : license,
            loaderForgeV                         : loaderForgeV,
            loaderForgeVRange                    : loaderForgeVRange,
            loaderNeoV                           : loaderNeoV,
            loaderNeoVRange                      : loaderNeoVRange,
            loaderFabricVRange                   : loaderFabricVRange,
            modId                                : modId,
            modV                                 : modV,
            modAuthors                           : modAuthorsDisplay,
            mcV                                  : mcV,
            mcVMin                               : mcVMin,
            mcVMax                               : mcVMax,
            modName                              : modName,
            gitUrl                               : gitUrl,
            curseUrl                             : curseUrl,
            discordUrl                           : discordUrl,
            modrinthUrl                          : modrinthUrl,
            modDesc                              : modDesc,
            modChanges                           : modChanges,
            loaderFabricForgeConfigApiPortVRange : loaderFabricForgeConfigApiPortVRange,
            javaV                                : javaV
    ]

    inputs.properties replaceProperties
    filesMatching(["META-INF/mods.toml", "META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
        expand replaceProperties
    }

    from configurations.commonResources
    setDuplicatesStrategy DuplicatesStrategy.EXCLUDE
}

tasks.withType(JavaCompile).configureEach {
    source configurations.commonJava
    dependsOn configurations.commonJava
}

tasks.withType(Javadoc).configureEach {
    dependsOn configurations.commonJava
    source configurations.commonJava
}

jar {
    from configurations.commonResources
    exclude "**/common_aw.accesswidener"
    setDuplicatesStrategy DuplicatesStrategy.EXCLUDE
}

tasks.named("sourcesJar", Jar) {
    from project(":loader:common").sourceSets.main.allSource
    exclude "**/common_aw.accesswidener"
    setDuplicatesStrategy DuplicatesStrategy.EXCLUDE
}

if (rootProject.file("secrets.properties").exists()) {
    afterEvaluate {
        publishMods {
            String name = project.name == "neoforge" ? "NeoForge" : project.name.capitalize()

            changelog = modChanges.replace("| ", "+ ")
            displayName = "${modName} ${modV} ${name} ${mcV}"

            file = tasks.named("jar").flatMap {
                it.archiveFile
            }

            type = STABLE

            additionalFiles.from tasks.named("sourcesJar").flatMap {
                it.archiveFile
            }

            modLoaders.add(project.name)

            curseforge {
                accessToken = findProperty("secretsCurseForgeToken")
                clientRequired = true
                projectId = "889368"
                serverRequired = true

                javaVersions.add(JavaVersion.toVersion(javaV))

                minecraftVersionRange {
                    start = mcVMin
                    end = mcVMax
                }

                if (project.name == "fabric") {
                    requires "fabric-api"
                    requires "forge-config-api-port"
                }
            }

            modrinth {
                accessToken = findProperty("secretsModrinthToken")
                projectId = "scvT0o5w"
                version = modV

                minecraftVersionRange {
                    start = mcVMin
                    end = mcVMax
                }

                if (project.name == "fabric") {
                    requires "fabric-api"
                    requires "forge-config-api-port"
                }
            }
        }
    }
}