plugins {
    id "common"
    id "java"
    id "me.modmuss50.mod-publish-plugin"
}

configurations {
    commonJava {
        canBeResolved true
    }

    commonResources {
        canBeResolved true
    }
}

dependencies {
    compileOnly(project(":loader:common")) {
        capabilities {
            requireCapability "${group}:${modId}"
        }
    }

    commonJava project(path: ":loader:common", configuration: "commonJava")
    commonResources project(path: ":loader:common", configuration: "commonResources")
}

processResources {
    dependsOn configurations.commonResources

    String modDesc =
            "${modSummary}\n" +
            "View the source code here: ${gitUrl}\n" +
            "Or visit the wiki here: ${gitUrl}/wiki\n" +
            "And join the discord here: ${discordUrl}";

    String modDescFabric = modSummary;

    if (!modChanges.empty) {
        String changes = "\n\nChanges this version:\n${modChanges}"
        modDesc += changes;
        modDescFabric += changes;
    }

    var replaceProperties = [
            license                              : license,
            loaderForgeV                         : loaderForgeV,
            loaderForgeVRange                    : loaderForgeVRange,
            loaderFabricVRange                   : loaderFabricVRange,
            modId                                : modId,
            modV                                 : modV,
            modAuthors                           : modAuthorsDisplay,
            mcV                                  : mcV,
            modName                              : modName,
            gitUrl                               : gitUrl,
            curseUrl                             : curseUrl,
            discordUrl                           : discordUrl,
            modrinthUrl                          : modrinthUrl,
            modDesc                              : modDesc,
            modDescFabric                        : modDescFabric,
            modChanges                           : modChanges,
            loaderFabricForgeConfigApiPortVRange : loaderFabricForgeConfigApiPortVRange,
            javaV                                : javaV
    ]

    inputs.properties replaceProperties
    filesMatching(["META-INF/mods.toml", "fabric.mod.json"]) {
        expand replaceProperties
    }

    from configurations.commonResources
    setDuplicatesStrategy DuplicatesStrategy.EXCLUDE
}

jar {
    from configurations.commonResources
    setDuplicatesStrategy DuplicatesStrategy.EXCLUDE
}

tasks.named("compileJava", JavaCompile) {
    dependsOn configurations.commonJava
    source configurations.commonJava
}

tasks.named("javadoc", Javadoc) {
    dependsOn configurations.commonJava
    source configurations.commonJava
}

tasks.named("sourcesJar", Jar) {
    from project(":loader:common").sourceSets.main.allSource
    setDuplicatesStrategy DuplicatesStrategy.EXCLUDE
}

if (rootProject.file("secrets.properties").exists()) {
    publishMods {
        changelog = modChanges.replace("| ", "+ ")
        displayName = "${modName} ${modV} ${project.name.capitalize()} ${mcV}"

        if (project.plugins.hasPlugin("fabric-loom-remap")) {
            file = project.tasks.named("remapJar").flatMap {
                it.archiveFile
            }
        } else {
            file = jar.archiveFile
        }

        type = STABLE

        additionalFiles.from(sourcesJar.archiveFile)
        modLoaders.add(project.name)

        curseforge {
            accessToken = findProperty("secretsCurseForgeToken")
            clientRequired = true
            projectId = "889368"
            serverRequired = true

            javaVersions.add(JavaVersion.toVersion(javaV))
            minecraftVersions.add(mcV)

            if (project.name == "fabric") {
                requires "fabric-api"
                requires "forge-config-api-port"
            }
        }

        modrinth {
            accessToken = findProperty("secretsModrinthToken")
            projectId = "scvT0o5w"
            version = modV

            minecraftVersions.add(mcV)

            if (project.name == "fabric") {
                requires "fabric-api"
                requires "forge-config-api-port"
            }
        }
    }
}