plugins {
    id "ohmega-platform"
}

jar {
    archiveClassifier = "api"
}

tasks.named ("javadocJar", Jar) {
    archiveClassifier = "api-javadoc-unused"
}

tasks.named ("pseudoJavadocJar", Jar) {
    archiveClassifier = "api-javadoc"
}

tasks.named ("sourcesJar", Jar) {
    archiveClassifier = "api-sources"
}