plugins {
    id "java-library"
}

group "com.swacky"
version "${modV}-mc${mcV}"

java {
    JavaLanguageVersion javaVersion = JavaLanguageVersion.of(javaV)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    toolchain.languageVersion = javaVersion

    // This artifact isn't used, it is just to error out if any Javadoc '{@link ...}' references are incorrect
    withJavadocJar()
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set JavaLanguageVersion.of(javaV).asInt()
}

jar {
    exclude "**/.cache"
}

javadoc {
    options {
        tags = [
                "apiNote:a:API Note:",
                "implSpec:a:Implementation Requirements:",
                "implNote:a:Implementation Note:"
        ]
    }
}

tasks.named ("sourcesJar", Jar) {
    exclude "**/.cache"
}

tasks.named ("compileTestJava") {
    enabled = false
}

tasks.named ("processTestResources") {
    enabled = false
}

["apiElements", "runtimeElements", "sourcesElements"].each { variant ->
    configurations."${variant}".outgoing {
        capability "${group}:${modId}-${project.name}:${version}"
    }
}

configurations {
    commonJava {
        canBeResolved true
        canBeConsumed true
    }

    commonResources {
        canBeResolved true
        canBeConsumed true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.files
}

static void includeProjectOutput(DependencyHandler handler, String projectPath) {
    handler.commonJava handler.project(path: projectPath, configuration: "commonJava")
    handler.commonResources handler.project(path: projectPath, configuration: "commonResources")
}

File accessWidenerFile(Project project) {
    return project.file("src/main/resources/${metaFileName(project)}.accesswidener")
}

void apiModuleDependency(DependencyHandler handler, Project apiProject) {
    String fixedGroup = group

    handler.compileOnlyApi (apiProject) {
        capabilities {
            requireCapability "${fixedGroup}:${modId}-${apiProject.name}"
        }
    }

    includeProjectOutput handler, apiProject.path
}

Project commonImplProject() {
    return rootProject.project("module:platform:common:common")
}

void compatModuleDependency(DependencyHandler handler, String name) {
    moduleDependency handler, compatProject(name)
}

Project compatProject(String name) {
    rootProject.project("module:compat:${name}")
}

String metaFileName(Project project) {
    return "${modId}_${project.name}"
}

String mixinConfigName(Project project) {
    return "${metaFileName(project)}.mixins.json"
}

void moduleDependency(DependencyHandler handler, Project dependency) {
    String fixedGroup = group

    handler.compileOnlyApi (dependency) {
        capabilities {
            requireCapability "${fixedGroup}:${modId}-${dependency.name}"
        }
    }

    includeProjectOutput handler, dependency.path
}

Project platformImplProject(String name) {
    return rootProject.project("module:platform:${name}:${name}")
}

ext.accessWidenerFile = this.&accessWidenerFile
ext.apiModuleDependency = this.&apiModuleDependency
ext.commonImplProject = this.&commonImplProject
ext.compatModuleDependency = this.&compatModuleDependency
ext.compatProject = this.&compatProject
ext.metaFileName = this.&metaFileName
ext.mixinConfigName = this.&mixinConfigName
ext.moduleDependency = this.&moduleDependency
ext.platformImplProject = this.&platformImplProject
