plugins {
    id "ohmega-module"
    id "maven-publish"
    id "signing"
}

base {
    archivesName.set "${modId}-${project.parent.name}"
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

tasks.named ("javadocJar", Jar) {
    archiveClassifier = "javadoc-unused"
}

tasks.register ("pseudoJavadocJar", Jar) {
    archiveClassifier = "javadoc"
}

processResources {
    LinkedHashMap<String, String> replacements = [
            modId          : modId,
            packFormatMaxV : packFormatMaxV,
            packFormatMinV : packFormatMinV
    ]

    inputs.properties replacements

    filesMatching (["pack.mcmeta", "resourcepacks/*/pack.mcmeta"]) {
        expand replacements
    }
}
