plugins {
    id "idea"
    id "java"
    id "net.fabricmc.fabric-loom" version "${pluginLoomV}" apply false
    id "net.minecraftforge.gradle" version "${pluginForgeV}"
    id "net.neoforged.moddev" version "${pluginNeoV}" apply false
}

idea {
    module {
        downloadJavadoc true
        downloadSources true
    }
}

File secretsFile = file("secrets.properties")

if (secretsFile.exists()) {
    secretsFile.withInputStream { stream ->
        {
            Properties secrets = new Properties()

            secrets.load(stream)
            secrets.forEach {
                key, value -> project.ext.set((String) key, value)
            }
        }
    }

    if (loaderEnabledFabric.toBoolean()) {
        //TaskProvider<Task> datagenTask = project("module:platform:fabric:fabric").tasks.named "runDatagen"

        subprojects.each { sub ->
            sub.tasks.matching {
                it.name == "publishMods"
            }.configureEach { publishTask ->
                //dependsOn datagenTask
                //mustRunAfter datagenTask
            }
        }
    }
}