org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# version+forge-mc_version_range
mod_version_file_display=1.3.0+forge-1.21-1.21.1
mod_version=1.3.0
mod_id=ohmega
minecraft_version=1.21.1
forge_version=52.0.15
mappings_channel=parchment
mappings_version=1.21-2024.06.23-1.21.1
mod_authors=swacky

loader_version_range=[51,53)
mod_authors_display=Swacky_
forge_version_range=[51,53)
minecraft_version_range=[1.21,1.21.2)