org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# todo: Complete scrolling overflow functionality for GUI
# todo: Add a config screen for Forge

javaV=21
mcV=1.21.9
packFormatMinV=0
packFormatMaxV=88
# https://projects.neoforged.net/neoforged/neoform
neoFormV=20250930.151910
loaderFabricVRange=>=0.15
loaderForgeVRange=[59,)
loaderNeoVRange=[21.9,)
loaderFabricForgeConfigApiPortVRange=>=21.9

loaderFabricV=0.18.4
loaderForgeV=59.0.5
loaderNeoV=21.9.16-beta
loaderFabricApiV=0.134.1
loaderFabricForgeConfigApiPortV=21.9.8
loaderFabricModMenuV=16.0.0-rc.2

mapsMcV=1.21.9
mapsV=2025.10.05

modV=1.5.11
# \t does not format correctly in fabric with ModMenu, nor does leading spaces, so a '| ' prefix is used
modChanges=\
  | Fixed accessory inventory not opening while joined on dedicated server

pluginLoomV=1.13-SNAPSHOT
pluginForgeV=[6.0.46, 6.2)
pluginNeoV=2.0.137

license=All rights reserved
modName=Ohmega
modId=ohmega
modAuthors=swacky
modAuthorsDisplay=Swacky_

gitUrl=https://github.com/Swackyy/Ohmega
curseUrl=https://www.curseforge.com/minecraft/mc-mods/ohmega
discordUrl=https://discord.gg/B9669WDmZk
modrinthUrl=https://modrinth.com/mod/ohmega
modSummary=A modernised and lightweight accessories API for Minecraft.
modDescSrc=View the source code here
modDescWiki=Or visit the wiki here
modDescDiscord=Discord server