org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# todo: Unify the AccessoryHelper class (as it is very loader dependant) with Java's ServiceLoader tool
# todo: Complete scrolling overflow functionality for GUI
# todo: Add a config screen for Forge

javaV=21
mcV=1.21.8
packFormatV=81
# https://projects.neoforged.net/neoforged/neoform
neoFormV=20250717.133445
loaderForgeVRange=[58,)
loaderNeoVRange=[21.8,)
loaderFabricVRange=>=0.15
loaderFabricForgeConfigApiPortVRange=>=21.8

loaderForgeV=58.1.0
loaderNeoV=21.8.52
loaderFabricV=0.18.1
loaderFabricApiV=0.136.1
loaderFabricForgeConfigApiPortV=21.8.2
loaderFabricModMenuV=15.0.0

mapsMcV=1.21.8
mapsV=2025.09.14

modV=1.4.5
# \t does not format correctly in fabric with ModMenu, nor does leading spaces, so a '| ' prefix is used
modChanges=| Fixed a few game crashing bugs\n| Fixed miscellaneous bugs\n| Fixed some config translations\n| Slightly improved performance\n| Registered a config menu for NeoForge

pluginForgeV=[6.0.24, 6.2)
pluginNeoV=2.0.122
pluginLoomV=1.11-SNAPSHOT

license=MIT
modName=Ohmega
modId=ohmega
modAuthors=swacky
modAuthorsDisplay=Swacky_

gitUrl=https://github.com/Swackyy/Ohmega
curseUrl=https://www.curseforge.com/minecraft/mc-mods/ohmega
discordUrl=https://discord.gg/B9669WDmZk
modrinthUrl=https://modrinth.com/mod/ohmega
modSummary=A modernized and lightweight accessories API for Minecraft.
modDescSrc=View the source code here
modDescWiki=Or visit the wiki here
modDescDiscord=Discord server