pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()

        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net"
        }

        maven {
            name = "Forge"
            url = "https://maven.minecraftforge.net"
        }

        maven {
            name = "NeoForge"
            url = "https://maven.neoforged.net/releases"
        }

        maven {
            name = "Sponge"
            url = "https://repo.spongepowered.org/repository/maven-public"
        }
    }
}

include "module:platform:common:api"
include "module:platform:common:impl"

boolean loaderEnabledFabric = loaderEnabledFabric.toBoolean()
boolean loaderEnabledForge = loaderEnabledForge.toBoolean()
boolean loaderEnabledNeo = loaderEnabledNeo.toBoolean()

if (loaderEnabledFabric) {
    include "module:platform:fabric:api"
    include "module:platform:fabric:impl"
}

if (loaderEnabledForge) {
    include "module:platform:forge:api"
    include "module:platform:forge:impl"
}

if (loaderEnabledNeo) {
    include "module:platform:neoforge:api"
    include "module:platform:neoforge:impl"
}

if (compatEnabledJei.toBoolean()) {
    include "module:compat:util:exclusion-zone"
    include "module:compat:jei"
}

if (compatEnabledPolymer.toBoolean()) {
    include "module:compat:polymer"
}

if (compatEnabledRei.toBoolean()) {
    include "module:compat:util:exclusion-zone"
    include "module:compat:rei:common"

    if (loaderEnabledFabric) {
        include "module:compat:rei:fabric"
    }

    if (loaderEnabledNeo) {
        include "module:compat:rei:neoforge"
    }
}

if (compatEnabledRrv.toBoolean()) {
    include "module:compat:util:exclusion-zone"
    include "module:compat:rrv:common"

    if (loaderEnabledFabric) {
        include "module:compat:rrv:fabric"
    }

    if (loaderEnabledNeo) {
        include "module:compat:rrv:neoforge"
    }
}

gradle.settingsEvaluated {
    rootProject.children.forEach { child ->
        eval(child)
    }
}

void eval(ProjectDescriptor child) {
    ProjectDescriptor grandparent = child.parent.parent

    if (grandparent != null) {
        String grandparentName = grandparent.name

        if (grandparentName == "compat") {
            child.setName "${child.parent.name}-${child.name}"
        } else if (grandparentName == "platform") {
            String originalName = child.name
            String parentName = child.parent.name

            if (originalName == "api") {
                child.setName "${parentName}-${originalName}"
            } else if (originalName == "impl") {
                child.setName parentName
            }
        }
    }

    child.children.forEach { subChild ->
        eval subChild
    }
}

rootProject.setName modName
