plugins {
    id "loader"
    id "net.minecraftforge.gradle" version "${pluginForgeV}"
}

minecraft {
    mappings channel: "official", version: mcV

    accessTransformer = true

    runs {
        configureEach {
            mods {
                "${modId}" {
                    source sourceSets.main
                    source project(":loader:common").sourceSets.main
                }
            }

            environment "MOD_CLASSES": "{source_roots}"
            args "--mixin.config", "${modId}.mixins.json"
            args "--mixin.config", "${modId}_common.mixins.json"
            systemProperty "eventbus.api.strictRuntimeChecks", "true"
            systemProperty "forge.enabledGameTestNamespaces", modId
            workingDir.convention layout.projectDirectory.dir("run")
        }

        register("client")

        register("server") {
            args "--nogui"
        }
    }
}

repositories {
    mavenCentral()
    minecraft.mavenizer it
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven

    maven {
        name = "Forge"
        url = "https://maven.minecraftforge.net"
    }
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${mcV}-${loaderForgeV}")

    annotationProcessor "net.minecraftforge:eventbus-validator:7.0-beta.7"
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "${modId}.mixins.json, ${modId}_common.mixins.json"
        ])
    }
}