plugins {
    id "loader"
    id "net.minecraftforge.gradle" version "${pluginForgeV}"
}

java {
    modularity.inferModulePath.set false
}

minecraft {
    mappings channel: "official", version: mcV

    accessTransformer = true

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir("run")
            systemProperty "eventbus.api.strictRuntimeChecks", "true"
            systemProperty "forge.enabledGameTestNamespaces", modId
            args "-mixin.config", "${modId}.mixins.json"
            args "-mixin.config", "${modId}_common.mixins.json"
        }

        register("client") {}

        register("server") {}
    }
}

repositories {
    mavenCentral()
    minecraft.mavenizer it
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven

    maven {
        name = "Forge"
        url = "https://maven.minecraftforge.net"
    }
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${mcV}-${loaderForgeV}")

    implementation "io.github.llamalad7:mixinextras-common:0.5.2"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.5.2"
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"

    runtimeOnly "org.ow2.asm:asm:9.5"
    runtimeOnly "org.ow2.asm:asm-tree:9.5"
    runtimeOnly "org.ow2.asm:asm-commons:9.5"
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "${modId}.mixins.json, ${modId}_common.mixins.json"
        ])
    }
}