plugins {
    id "loader"
    id "net.minecraftforge.gradle"
    id "org.parchmentmc.librarian.forgegradle" version "1.+"
    id "org.spongepowered.mixin" version "0.7.+"
}

version = "forge+${mcV}"

mixin {
    config "${modId}.mixins.json"
    config "${modId}_common.mixins.json"
}

minecraft {
    if (mapsMcV == mcV) {
        mappings channel: "parchment", version: "${mapsV}-${mapsMcV}"
    } else {
        mappings channel: "parchment", version: "${mapsMcV}-${mapsV}-${mcV}"
    }

    reobf = false
    accessTransformer = file "src/main/resources/META-INF/accesstransformer.cfg"

    copyIdeResources.set true

    runs {
        configureEach {
            ideaModule = "${rootProject.name}.loader.${project.name}.main"

            workingDirectory file("run")
            property "forge.enabledGameTestNamespaces", "${modId}"
            property "eventbus.api.strictRuntimeChecks", "true"
        }

        client {}

        server {}
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${mcV}-${loaderForgeV}"

    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
    annotationProcessor "net.minecraftforge:eventbus-validator:7.0-beta.7"

    implementation("net.sf.jopt-simple:jopt-simple:5.0.4") {
        version {
            strictly "5.0.4"
        }
    }
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "${modId}.mixins.json, ${modId}_common.mixins.json"
        ])
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir

    it.java.destinationDirectory.set dir.get()
}