modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="ohmega" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ohmega" #mandatory
logoFile="ohmega.png" #optional
credits="Inspired by other accessorising mods which felt they needed something more" #optional
authors="Developer: Swacky_" #optional
description='''
A modernized and lightweight accessories mod for Minecraft
For API usage and reference code info, visit github.com/
'''
[[dependencies.ohmega]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ohmega]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
