modLoader="javafml"
loaderVersion="[44,45)"
license="All rights reserved"
[[mods]]
modId="ohmega"
version="${file.jarVersion}"
displayName="Ohmega"
logoFile="ohmega.png"
#credits=""
authors="Developer: Swacky_"
description='''
A modernized and lightweight accessories mod for Minecraft. For API usage and reference code info, visit https://github.com/Swackyy/ohmega and view the readme.md file'''
[[dependencies.ohmega]]
    modId="forge"
    mandatory=true
    versionRange="[44,45)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ohmega]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.19.4)"
    ordering="NONE"
    side="BOTH"
