modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Ohmega"
logoFile= "${mod_id}.png"
authors="${mod_authors}"
description='''A modernized and lightweight accessories API for Minecraft.
View the source code here: https://github.com/Swackyy/ohmega
Or visit the wiki here: https://github.com/Swackyy/Ohmega/wiki'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
