plugins {
    id "ohmega-compat"
    id "java-library"
}

repositories {
    maven {
        name = "BlameJared"
        url = "https://maven.blamejared.com"
    }
}

dependencies {
    compatModuleDependency it, "util:util-exclusion-zone"
    compileOnlyApi "mezz.jei:jei-${mcV}-common-api:${compatJeiV}"
}