plugins {
    id "java-library"
    id "ohmega-compat"
}

repositories {
    maven {
        name = "Cassian"
        url = "https://maven.cassian.cc"
    }
}

dependencies {
    compatModuleDependency(it, "util_exclusion-zones")
    compileOnlyApi "cc.cassian.rrv:reliable-recipe-viewer-neoforge:${compatRrvV}+${mcV}"
}