modLoader="javafml"
loaderVersion="${loaderNeoV}"
issueTrackerURL="${gitUrl}/issues"
license="${license}"


[[mods]]
modId="${modId}"
version="${modV}"
displayName="${modName}"
displayURL="${gitUrl}"
logoFile= "${modId}.png"
authors="${modAuthors}"
description='''${modDesc}'''


[[mixins]]
config="${modId}.mixins.json"

[[mixins]]
config="${modId}_common.mixins.json"


[[dependencies.${modId}]]
modId="neoforge"
type="required"
versionRange="${loaderNeoVRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="[${mcVRangeMin},${mcVRangeMax}]"
ordering="NONE"
side="BOTH"