plugins {
    id "loader"
    id "net.neoforged.moddev" version "${pluginNeoV}"
}

version "neoforge+${mcV}"

neoForge {
    version.set loaderNeoV

    accessTransformers {
        file("src/main/resources/META-INF/accesstransformer.cfg")
    }

    mods {
        "${modId}" {
            sourceSet sourceSets.main
            sourceSet project(":loader:common").sourceSets.main
        }
    }

    parchment {
        mappingsVersion.set mapsV
        minecraftVersion.set mapsMcV
    }

    runs {
        configureEach {
            systemProperty "neoforge.enabledGameTestNamespaces", "${modId}"
            systemProperty "forge.logging.markers", "REGISTRIES"

            ideName.set "NeoForge ${it.name.capitalize()} (${project.path}"
        }

        client {
            client()
        }

        server {
            server()
        }

        clientData {
            ideName.set "Data Generation"
            clientData()
            programArguments.addAll "--mod", "${modId}", "--all", "--output", project(":loader:common").getDependencyProject().sourceSets.main.resources.getSourceDirectories().getFiles()[1].getAbsolutePath() , "--existing", project(":loader:common").getDependencyProject().sourceSets.main.resources.getSourceDirectories().getFiles()[0].getAbsolutePath()
        }
    }
}