plugins {
    id "loader"
    id "net.neoforged.moddev"
}

neoForge {
    version = loaderNeoV

    accessTransformers {
        file "src/main/resources/META-INF/accesstransformer.cfg"
    }

    mods {
        "${modId}" {
            sourceSet sourceSets.main
            sourceSet project(":loader:common").sourceSets.main
        }
    }

    parchment {
        mappingsVersion.set mapsV
        minecraftVersion.set mapsMcV
    }

    runs {
        configureEach {
            ideName.set "NeoForge ${it.name.capitalize()} (${project.path})"
            systemProperty "neoforge.enabledGameTestNamespaces", modId
        }

        client {
            client()
        }

        server {
            server()
        }

        data {
            data()

            ideName.set "Data Generation"
            programArguments.addAll "--mod", "${modId}", "--all", "--output", project.project(":loader:common").file("src/main/generated").getAbsolutePath() , "--existing", project.project(":loader:common").file("src/main/resources").getAbsolutePath()
        }
    }
}

tasks.named("compileTestJava") {
    enabled = false
}