plugins {
    id "java-library"
    id "ohmega-compat"
}

repositories {
    maven {
        name = "Architectury"
        url = "https://maven.architectury.dev"
    }
}

dependencies {
    compatModuleDependency it, "util:util-exclusion-zone"
    compileOnly "me.shedaniel:RoughlyEnoughItems-api:${mcV}.${compatReiV}"
}