plugins {
    id "loader"
    id "net.fabricmc.fabric-loom" version "${pluginLoomV}"
}

loom {
    accessWidenerPath = file "src/main/resources/aw.accesswidener"

    runs {
        configureEach {
            property "mixin.debug.export", "true"
            setConfigName "Fabric ${it.name.capitalize()}"

            runDir = "run"
            ideConfigGenerated = true
        }

        client {
            client()

            programArgs "--username", "Dev"
        }

        client2 {
            client()

            programArgs "--username", "AlsoDev"
        }

        server {
            server()
        }
    }
}

repositories {
    maven {
        name = "BlameJared"
        url = "https://maven.blamejared.com"
    }

    maven {
        name = "Fuzss"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven"
    }

    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/releases"
    }

    maven {
        name = "Parchment"
        url = "https://maven.parchmentmc.org"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${mcV}"

    implementation "net.fabricmc:fabric-loader:${loaderFabricV}"
    implementation "net.fabricmc.fabric-api:fabric-api:${loaderFabricApiV}+${mcV}"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${loaderFabricForgeConfigApiPortV}"

    compileOnly "mezz.jei:jei-${mcV}-fabric-api:${jeiV}"
    runtimeOnly "mezz.jei:jei-${mcV}-fabric:${jeiV}"

    implementation "com.terraformersmc:modmenu:${loaderFabricModMenuV}"
}

fabricApi {
    configureDataGeneration {
        client = true
        modId = project.modId
        outputDirectory = file project(":loader:common").sourceSets.main.resources.getSourceDirectories().getFiles()[1].getAbsolutePath()
    }
}