plugins {
    id "net.fabricmc.fabric-loom-remap" version "${pluginLoomV}"
    id "loader"
}

loom {
    accessWidenerPath.set file("src/main/resources/aw.accesswidener")

    runs {
        configureEach {
            setConfigName "Fabric ${it.name.capitalize()}"

            runDir = "run"
            ideConfigGenerated = true
        }

        client {
            client()

            programArgs "--username", "Dev"
        }

        server {
            server()
        }
    }
}

remapSourcesJar {
    targetNamespace = "named"
}

repositories {
    maven {
        name = "Config API"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven"
    }

    maven {
        name = "ModMenu"
        url = "https://maven.terraformersmc.com/releases"
    }

    maven {
        name = "Nucleoid"
        url = "https://maven.nucleoid.xyz"
    }

    maven {
        name = "Parchment"
        url = "https://maven.parchmentmc.org"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${mcV}"

    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${mapsMcV}:${mapsV}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${loaderFabricV}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${loaderFabricApiV}+${mcV}"
    modImplementation "com.terraformersmc:modmenu:${loaderFabricModMenuV}"
    modImplementation "net.minecraftforge:forgeconfigapiport-fabric:${loaderFabricForgeConfigApiPortV}"
    implementation "com.electronwill.night-config:core:3.6.4"
    implementation "com.electronwill.night-config:toml:3.6.4"
}

fabricApi {
    configureDataGeneration {
        outputDirectory = file project(":loader:common").sourceSets.main.resources.getSourceDirectories().getFiles()[1].getAbsolutePath()
    }
}